#pragma once
#include "Util/Managed.h"
#include "Util/Span.h"
#include "Util/String.h"

typedef enum
{
	TOKEN_EOF,
	TOKEN_UNEXPECTED,
	TOKEN_WHITESPACE,
	TOKEN_COMMENT_SINGLELINE,
	TOKEN_COMMENT_MULTILINE,

	TOKEN_LITERAL_INTEGER,
	TOKEN_LITERAL_FLOAT,
	TOKEN_LITERAL_STRING,

	TOKEN_IDENTIFIER,

	// Keywords: types
	TOKEN_KEYWORD_CHAR,
	TOKEN_KEYWORD_DOUBLE,
	TOKEN_KEYWORD_FLOAT,
	TOKEN_KEYWORD_INT,
	TOKEN_KEYWORD_LONG,
	TOKEN_KEYWORD_SHORT,
	TOKEN_KEYWORD_VOID,

	// Keywords: qualifiers
	TOKEN_KEYWORD_CONST,
	TOKEN_KEYWORD_VOLATILE,
	TOKEN_KEYWORD_SIGNED,
	TOKEN_KEYWORD_UNSIGNED,
	TOKEN_KEYWORD_RESTRICT,

	// Keywords: storage classes
	TOKEN_KEYWORD_AUTO,
	TOKEN_KEYWORD_EXTERN,
	TOKEN_KEYWORD_REGISTER,
	TOKEN_KEYWORD_STATIC,
	TOKEN_KEYWORD_TYPEDEF,

	// Keywords: function specifiers
	TOKEN_KEYWORD_INLINE,

	// Keywords: structures
	TOKEN_KEYWORD_STRUCT,
	TOKEN_KEYWORD_UNION,
	TOKEN_KEYWORD_ENUM,

	// Keywords: control flow
	TOKEN_KEYWORD_IF,
	TOKEN_KEYWORD_ELSE,
	TOKEN_KEYWORD_SWITCH,
	TOKEN_KEYWORD_CASE,
	TOKEN_KEYWORD_DEFAULT,

	// Keywords: loops/jumps
	TOKEN_KEYWORD_FOR,
	TOKEN_KEYWORD_DO,
	TOKEN_KEYWORD_WHILE,
	TOKEN_KEYWORD_BREAK,
	TOKEN_KEYWORD_CONTINUE,
	TOKEN_KEYWORD_GOTO,
	TOKEN_KEYWORD_RETURN,

	// Keywords: operators
	TOKEN_KEYWORD_SIZEOF,

	// Punctuators: single-character
	TOKEN_PUNCTUATOR_EQUAL, // '='
	TOKEN_PUNCTUATOR_PLUS, // '+'
	TOKEN_PUNCTUATOR_MINUS, // '-'
	TOKEN_PUNCTUATOR_ASTERISK, // '*'
	TOKEN_PUNCTUATOR_SLASH, // '/'INT
	TOKEN_PUNCTUATOR_PERCENT, // '%'
	TOKEN_PUNCTUATOR_AMPERSAND, // '&'
	TOKEN_PUNCTUATOR_PIPE, // '|'
	TOKEN_PUNCTUATOR_CARET, // '^'
	TOKEN_PUNCTUATOR_TILDE, // '~'
	TOKEN_PUNCTUATOR_EXCLAMATION, // '!'
	TOKEN_PUNCTUATOR_HASH, // '#'
	TOKEN_PUNCTUATOR_LESS, // '<'
	TOKEN_PUNCTUATOR_GREATER, // '>'
	TOKEN_PUNCTUATOR_PERIOD, // '.'
	TOKEN_PUNCTUATOR_COMMA, // ','
	TOKEN_PUNCTUATOR_SEMICOLON, // ';'
	TOKEN_PUNCTUATOR_PARENOPEN, // '('
	TOKEN_PUNCTUATOR_PARENCLOSE, // ')'
	TOKEN_PUNCTUATOR_BRACEOPEN, // '{'
	TOKEN_PUNCTUATOR_BRACECLOSE, // '}'
	TOKEN_PUNCTUATOR_BRACKETOPEN, // '['
	TOKEN_PUNCTUATOR_BRACKETCLOSE, // ']'
	TOKEN_PUNCTUATOR_DOUBLEQUOTE, // '"'
	TOKEN_PUNCTUATOR_SINGLEQUOTE, // '\''

	// Punctuators: two-character
	TOKEN_PUNCTUATOR_EQUAL_EQUAL, // '=='
	TOKEN_PUNCTUATOR_EXCLAMATION_EQUAL, // '!='
	TOKEN_PUNCTUATOR_LESS_EQUAL, // '<='
	TOKEN_PUNCTUATOR_GREATER_EQUAL, // '>='
	TOKEN_PUNCTUATOR_PLUS_PLUS, // '++'
	TOKEN_PUNCTUATOR_MINUS_MINUS, // '--'
	TOKEN_PUNCTUATOR_PLUS_EQUAL, // '+='
	TOKEN_PUNCTUATOR_MINUS_EQUAL, // '-='
	TOKEN_PUNCTUATOR_ASTERISK_EQUAL, // '*='
	TOKEN_PUNCTUATOR_SLASH_EQUAL, // '/='
	TOKEN_PUNCTUATOR_PERCENT_EQUAL, // '%='
	TOKEN_PUNCTUATOR_AMPERSAND_EQUAL, // '&='
	TOKEN_PUNCTUATOR_PIPE_EQUAL, // '|='
	TOKEN_PUNCTUATOR_CARET_EQUAL, // '^='
	TOKEN_PUNCTUATOR_AMPERSAND_AMPERSAND, // '&&'
	TOKEN_PUNCTUATOR_PIPE_PIPE, // '||'
	TOKEN_PUNCTUATOR_LESS_LESS, // '<<'
	TOKEN_PUNCTUATOR_GREATER_GREATER, // '>>'

	// Punctuators: three-character
	TOKEN_PUNCTUATOR_LESS_LESS_EQUAL, // '<<='
	TOKEN_PUNCTUATOR_GREATER_GREATER_EQUAL, // '>>='

	TOKEN_MAX
} Token_Type;

typedef enum
{
	TOKEN_LITERAL_FLOAT_TYPE_DOUBLE,
	TOKEN_LITERAL_FLOAT_TYPE_FLOAT,
	TOKEN_LITERAL_FLOAT_TYPE_LONGDOUBLE,
	TOKEN_LITERAL_FLOAT_TYPE_BINARY16,
	TOKEN_LITERAL_FLOAT_TYPE_BINARY32,
	TOKEN_LITERAL_FLOAT_TYPE_BINARY64,
	TOKEN_LITERAL_FLOAT_TYPE_DECIMAL32,
	TOKEN_LITERAL_FLOAT_TYPE_DECIMAL64,
	TOKEN_LITERAL_FLOAT_TYPE_DECIMAL128,
} Token_LiteralFloat_Type;

typedef enum
{
	TOKEN_LITERAL_INTEGER_TYPE_INT,
	TOKEN_LITERAL_INTEGER_TYPE_LONG,
	TOKEN_LITERAL_INTEGER_TYPE_LONGLONG,
	TOKEN_LITERAL_INTEGER_TYPE_UNSIGNEDINT,
	TOKEN_LITERAL_INTEGER_TYPE_UNSIGNEDLONG,
	TOKEN_LITERAL_INTEGER_TYPE_UNSIGNEDLONGLONG,
} Token_LiteralInteger_Type;

typedef struct
{
	ConstCharSpan value;
	size_t base;
	Token_LiteralInteger_Type type;
} Token_LiteralInteger;

typedef struct
{
	bool isHex;

	bool hasIntegerPart;
	ConstCharSpan integerPart;

	bool hasFractionalPart;
	ConstCharSpan fractionalPart;

	bool hasExponent;
	bool exponentIsNegative;
	ConstCharSpan exponentPart;

	Token_LiteralFloat_Type type;
} Token_LiteralFloat;

typedef struct
{
	Token_Type type;
	ConstCharSpan lexeme;
	size_t line;
	size_t column;

	union
	{
		Token_LiteralInteger literalInteger;
		Token_LiteralFloat literalDecimalFloat;
	};
} Token;

String* Token_LiteralString_GetValue(const Token* token);
ConstCharSpan Token_LiteralInteger_Get(const Token* token);
